require 'bits_service/routes/app_stash'
require 'bits_service/routes/base'
require 'bits_service/routes/buildpack_cache'
require 'bits_service/routes/buildpacks'
require 'bits_service/routes/droplets'
require 'bits_service/routes/packages'
